
--1) what is total revenue generated by male vs female customer
select  gender ,sum(purchase_amount) as total_sales
from analytics
group by gender ;

--2) which customer is used a discound but still spend more than avg purcharse amount?
select customer_id ,purchase_amount 
from analytics 
where discount_applied='Yes'
and 
purchase_amount >(select avg(purchase_amount) from analytics);

--3)which are the top 5 products with the highest avg review rating
select top 5 item_purchased ,round(avg(review_rating),2) as avg_rate
from analytics
group by item_purchased 
order by avg_rate desc;

--4)compare the avg purchase amount between the standard and express shipping
select shipping_type, avg(purchase_amount)
from analytics
where shipping_type in ('Express','Standard')
group by shipping_type;

--5)Do subscribe customer spend more? compare avg spend and total revenue bet subscribers and non-subscribers.
select subscription_status ,
count(customer_id ) as total_custmores,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from analytics
where  subscription_status in ('Yes','No')
group by  subscription_status

--6)which 5 products have  the highest percentage of purchase with discount applied?
select  top 5 item_purchased,
100* sum(case when discount_applied = 'Yes' then 1 else 0 end) /count(*)  as da
from analytics
group by item_purchased
order by da desc;

--7)segment customer into new ,returning and loyal based on thier total numbers
-- of previous purchase and show the count of each segemnt.
with cte as(
    select customer_id ,previous_purchases,
    case when previous_purchases=1 then 'New'
         when previous_purchases between 2 and 10 then 'returning'
         else 'loyal'
         end as rn
     from analytics
     )
select  rn ,count(*) as total_count
from cte
group by rn;




